stages:
  cvat_xml_to_ultralytics_instance:
    cmd: >-
      python -m databox.segmentation.cvat_xml_to_ultralytics_instance
      --input-root /home/fkwong/datasets/012_vehicle-insts/data/raw/bev_260708-260729
      --output-root /home/fkwong/datasets/012_vehicle-insts/data/prepared/ultralytics
      --config params.yaml
      --param-name cvat_xml_to_ultralytics_instance
    deps:
      - databox/segmentation/cvat_xml_to_ultralytics_instance.py
      - /home/fkwong/datasets/012_vehicle-insts/data/raw/bev_260708-260729
      - params.yaml
    params:
      - cvat_xml_to_ultralytics_instance
    outs:
      - /home/fkwong/datasets/012_vehicle-insts/data/prepared/ultralytics/images
      - /home/fkwong/datasets/012_vehicle-insts/data/prepared/ultralytics/labels
      - /home/fkwong/datasets/012_vehicle-insts/data/prepared/ultralytics/data.yaml
